### ISSUE TITLE
[Fundraise] Inconsistent pricing for "1 night of sleep" computation

### ISSUE THREAD

**Issue by mop13** [sleepbusorg/sleepbus.org#89]
### Title
[Fundraise] Inconsistent pricing for "1 night of sleep" computation
### Platform / OS 
Windows 10
### Browser
Chrome
### Description
The pricing for 1 night of sleep in donate is $55 but on fundraise campaign goal it shows 550 for 20 people (so 27.50 per 1 night of sleep)
### Steps to Reproduce

1. Go to donate page and take note of pricing -- https://www.sleepbus.org/donate
2. Go to fundraise page and notice the campaign goal computation -- https://www.sleepbus.org/fundraise

### Expected Behavior 
Consistent pricing all through out the page (whether 27.5 or 55)
### Additional Info
Related to this issue: #71

what is the default amount for 1 safe sleep 55 or 27.5? from there computation can be made for monthly and yearly default

Branch: 3df28384163f3c9dc262b86f61139745073d1332
dev Build: https://circleci.com/gh/sleepbusorg/sleepbus.org/128

**Comment by leonstafford** [comment]
From Simon:

>  No, that's not right. Not sure where that came from. Should be $10,037 for one year as a default for that section. $55 for two sleeps everywhere else

**Comment by mop13** [comment]
- [ ] https://www.sleepbus.org/donate -- it says 1 safe sleep for 55
- [ ] https://www.sleepbus.org/one-year-safe-sleep -- default amount used is 20,075 intstead of 10,037.5
- [ ] https://dev.sleepbus.org/donate -- monthly description says all year long

**Comment by leonstafford** [comment]
rm'd these 2 as they're OK

`- [ ] https://www.sleepbus.org/donate -- monthly description says all year long`

monthly, all year long. Like the Lionel Ritchie song 😺 

`- [ ] https://www.sleepbus.org/donate -- default amount for monthly is 55 instead of 852.5 for 31 days (1month)`

$55 AUD / month, so once a month payments of $55. Again, the $27.50 is the actual one-night sleep, $55 offered as placeholder, recommended donation amount.
